### ISSUE TITLE
Watch your grammar, young man.

### ISSUE THREAD

**Issue by bradicus1036** [charliewynn/language-repgen#1]
When the repgen grammar package is enabled , the closing parenthesis/bracket/brace of any other grammar is colored orange.

![image](https://user-images.githubusercontent.com/33078931/32347044-6942541a-bfdd-11e7-939c-58ea497f6c69.png)

![image](https://user-images.githubusercontent.com/33078931/32347072-81a88ace-bfdd-11e7-839e-4c99531bde6d.png)

**Comment by charliewynn** [comment]
Fixed via #1732fda96f8936eb45c8851f472e280adc1b7579
